### ISSUE TITLE
request for dkms version

### ISSUE THREAD

**Issue by aquilarubra** [lwfinger/rtw8852cu#1]
Hi, could you make a dkms version?

I can make Arch packages (AUR) for both.

**Comment by lwfinger** [comment]
I do not do dkms. If you want to prepare the necessary routines, I will incorporate them.

**Comment by aquilarubra** [comment]
Ok, I found the way to just create the dkms package, no need to branch source.

This is for Arch Linux.

Kernel module:
https://aur.archlinux.org/packages/rtl8852cu-git

DKMS module:
https://aur.archlinux.org/packages/rtl8852cu-dkms-git

**Comment by lwfinger** [comment]
OK.
