### ISSUE TITLE
Seeing Two SSIDs in the AP mode for RTL8852CU 

### ISSUE THREAD

**Issue by madhug89** [lwfinger/rtw8852cu#11]
Right now I am trying to bring up this driver for USB based dongle RTL8852CU. 

The module is working fine in the STA mode but when I am trying to configure this module as SoftAP by using hostapd, then I am observing the two SSID's with the same name with different MAC addresses.

Please find the hostapd configs are below - 

logger_syslog=-1
logger_syslog_level=2
logger_stdout=0
logger_stdout_level=5
ap_isolate=1
ap_max_inactivity=30
disassoc_low_ack=1

interface=wlan0
driver=nl80211
channel=11

country_code=IN
ieee80211d=1
ieee80211h=1

beacon_int=200
supported_rates=120 180 240 360 480 540
basic_rates=120 180 240 360 480 540

# g is needed, n is built on top of it
hw_mode=g

# this enables the 802.11n speeds and capabilities ...  You will also need to enable WMM for full HT functionality.
ieee80211n=1

# Low priority / AC_BK = background
tx_queue_data3_aifs=7
tx_queue_data3_cwmin=63
tx_queue_data3_cwmax=1023
tx_queue_data3_burst=0
# Note: for IEEE 802.11b mode: cWmin=31 cWmax=1023 burst=0
#
# Normal priority / AC_BE = best effort
tx_queue_data2_aifs=3
tx_queue_data2_cwmin=63
tx_queue_data2_cwmax=255
tx_queue_data2_burst=0
# Note: for IEEE 802.11b mode: cWmin=31 cWmax=127 burst=0
#
# High priority / AC_VI = video
tx_queue_data1_aifs=1
tx_queue_data1_cwmin=7
tx_queue_data1_cwmax=15
tx_queue_data1_burst=3.0
# Note: for IEEE 802.11b mode: cWmin=15 cWmax=31 burst=6.0
#
# Highest priority / AC_VO = voice
tx_queue_data0_aifs=1
tx_queue_data0_cwmin=3
tx_queue_data0_cwmax=7
tx_queue_data0_burst=1.5
# Note: for IEEE 802.11b mode: cWmin=7 cWmax=15 burst=3.3

wmm_enabled=1
wme_enabled=1

# Low priority / AC_BK = background
wmm_ac_bk_cwmin=6
wmm_ac_bk_cwmax=10
wmm_ac_bk_aifs=7
wmm_ac_bk_txop_limit=0
wmm_ac_bk_acm=0
# Note: for IEEE 802.11b mode: cWmin=5 cWmax=10
#
# Normal priority / AC_BE = best effort
wmm_ac_be_aifs=3
wmm_ac_be_cwmin=6
wmm_ac_be_cwmax=10
wmm_ac_be_txop_limit=0
wmm_ac_be_acm=0
# Note: for IEEE 802.11b mode: cWmin=5 cWmax=7
#
# High priority / AC_VI = video
wmm_ac_vi_aifs=2
wmm_ac_vi_cwmin=4
wmm_ac_vi_cwmax=5
wmm_ac_vi_txop_limit=94
wmm_ac_vi_acm=0
# Note: for IEEE 802.11b mode: cWmin=4 cWmax=5 txop_limit=188
#
# Highest priority / AC_VO = voice
wmm_ac_vo_aifs=2
wmm_ac_vo_cwmin=3
wmm_ac_vo_cwmax=4
wmm_ac_vo_txop_limit=47
wmm_ac_vo_acm=0
# Note: for IEEE 802.11b mode: cWmin=3 cWmax=4 burst=102

# Enable 300 mbit
# ht_capab=[SHORT-GI-20][SHORT-GI-40][HT40-][TX-STBC][RX-STBC12]

# Set up some sane defaults:
# For packets over $val bytes, activate Request to Send (RTS) / Clear to Send (CTS)
# (CTS)
# Defaults to the frame size = 2347
#rts_threshold=1200

# For packets over $val bytes, fragment the packet into multiple frames. Half
# the Ethernet MTU (usually =1500) would normally be a good starting point, but we have only
# WiFi
# Defaults to the frame size = 2346
#fragm_threshold=1198

# Short preamble, improves performance IFF all STAs support it
# Defaults to $val=0 (off)
preamble=1

# DTIM (delivery traffic information message) period (range 1..255):
# number of beacons between DTIMs (1 = every beacon includes DTIM element)
# Note that multicast traffic is only sent with each DTIM. We could improve
# this by setting =1, but then STAs may never sleep again (drains power!)
# Defaults to $val=2 (once every two beacons)
dtim_period=3

# Wireless network management (WNM)
wnm_sleep_mode=1
bss_transition=1

#macaddr_acl=0
#accept_mac_file=/etc/hostapd.accept
#deny_mac_file=/etc/hostapd.deny

ssid=Test-2G
ctrl_interface=/var/run/hostapd
wpa=2
wpa_passphrase=diegheim9Aiqu4oomoo2hish9ohKae
wpa_key_mgmt=WPA-PSK-SHA256 WPA-PSK
wpa_pairwise=CCMP

Note: I didn't enable the Concurrent mode in the driver 

I need your valuable suggestions here

**Comment by lwfinger** [comment]
I have no experience with the vendor driver (the one you are using) in AP mode, and I provide this driver for the user's convenience, but my support is merely making sure that the driver will compile on everyone's kernel.

A references that may help:
https://github.com/haraldrudell/AC1300-USB

**Comment by madhug89** [comment]
Thanks @lwfinger  or your quick response !!

How did you get this realtek driver code?

**Comment by lwfinger** [comment]
I am not certain where I got that driver. Some models drivers came from one of my contacts at Realtek, while others came from vendors of the particular device.

**Comment by madhug89** [comment]
This issue is due to the manipulation of the original MAC address from our user space application.

So, closing this issue.
