### ISSUE TITLE
REGULATORY_IGNORE_STALE_KICKOFF error

### ISSUE THREAD

**Issue by aquilarubra** [lwfinger/rtw8852cu#3]
I got back my dongle and tested the new fix. It won't compile.

usr/src/rtw8852cu/os_dep/linux/wifi_regd.c: In function ‘rtw_regd_init’:
/usr/src/rtw8852cu/os_dep/linux/wifi_regd.c:1271:36: error: ‘REGULATORY_IGNORE_STALE_KICKOFF’ undeclared (first use in this function)
 1271 |         wiphy->regulatory_flags |= REGULATORY_IGNORE_STALE_KICKOFF;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/rtw8852cu/os_dep/linux/wifi_regd.c:1271:36: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:252: /usr/src/rtw8852cu/os_dep/linux/wifi_regd.o] Error 1
make[1]: *** [Makefile:2032: /usr/src/rtw8852cu] Error 2
make: *** [Makefile:705: modules] Error 2

**Comment by aquilarubra** [comment]
os_dep/linux/wifi_regd.c

Comment out this and it compiles.

/*
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 19, 0))
        wiphy->regulatory_flags |= REGULATORY_IGNORE_STALE_KICKOFF;
#endif
*/

I saw it commented out in other similar drivers.

**Comment by aquilarubra** [comment]
By the way, 6Ghz still does not work.

**Comment by lwfinger** [comment]
That I cannot help you with as I have no hardware.

**Comment by berc** [comment]
Seems for me like commit path for enabling 6Ghz was not done correctly.
Please see few lines below of the change from commit https://github.com/lwfinger/rtw8852cu/commit/34ac65b88bbdee123b2618a2b1b854c760b1a680

```cpp
#define CONFIG_IEEE80211_BAND_5GHZ 1
#define CONFIG_IEEE80211_BAND_6GHZ 1      // change

#ifndef CONFIG_IEEE80211_BAND_6GHZ
#define CONFIG_IEEE80211_BAND_6GHZ 0.    // <--------- revert the meaning of the change
```
