### ISSUE TITLE
This project can fail to compile on AARCH64 devices, such as Raspberry Pi 3B+ with RaspberryOS 64

### ISSUE THREAD

**Issue by zyuelin** [lwfinger/rtw8852cu#4]
I have a Raspberry Pi 3B+, git cloned this project, and want to compile it. But it encountered a failure, prompting an unsupported architecture. So, how do I deal with this error?
Thanks。

**Comment by DavidIlie** [comment]
Same here, anyone has found anything? I have a RTL8832CU which supposedly would work with this according [here](https://www.spinics.net/lists/linux-wireless/msg236330.html)

**Comment by lwfinger** [comment]
It is an easy fix that was not anticipated by the people at Realtek. The Makefile uses 'uname -m' to get the base directory for the architecture-specific code. Unfortunately, the device yields something different that the simple "arm" used by the kernel code.

Do a 'git pull' and it should be OK.

**Comment by DavidIlie** [comment]
Got it working thank you!

**Comment by zyuelin** [comment]
@lwfinger  Thanks. I will try it.

**Comment by zyuelin** [comment]
@lwfinger  
It  still not working.
![image](https://github.com/lwfinger/rtw8852cu/assets/145344671/0cb2feda-7ae4-4efa-ae46-3d962cc9c784)
$ uname -m 
![image](https://github.com/lwfinger/rtw8852cu/assets/145344671/955b06b4-1e45-4a82-8e84-a29d5a43567a)

I think the reason for the failure is that the result of uname -m execution is aarch64, but there is no aarch64/ directory in /usr/src/linux-headers-6.1.21-v8+/arch/, only the arm64/ directory. I renamed the arm64/ directory to aarch64, and the compilation worked normally.

**Comment by lwfinger** [comment]
In the future, do not send a message that you will try a fix. I get too many E-mails already.  Just try it and tell me if it fails.

The Makefile still had an error.Do a 'git pull', rename that directory back to the original, and try again.

**Comment by zyuelin** [comment]
I am so sorry to  bother you .
After I did the git pull operation, I still got the same error message.
It seems that the SUBARCH variable and ARCH variable in the Makefile are not assigned correctly. It is still aarch64, but arm64 is not obtained as expected. After I manually modified the ARCH variable to arm64, the compilation was normal.
